/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMe */

#ifndef _Included_NativeMe
#define _Included_NativeMe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMe
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMe_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
